"""Maintain the ability icons for the Execute (zhan sha) passive.

The **colored** icon is delivered artwork and is NOT generated by this script:

  assets/beloong/textures/gui/sprites/abilities/execute_1.png    (shown at ability level >= 1)
  assets/beloong/textures/gui/sprites/abilities/execute_0.png    (shown at ability level 0 -- derived below)

This script only derives the **locked** (level 0) icon from the delivered one, because the
project convention -- shared with air_strike / tornado / tp_loong_palace -- is that the level-0
icon is the same image desaturated to pure grayscale.

That convention is measured, not assumed: all four pre-existing level-0 icons have saturation
exactly 0.000 while their luminance ratio L0/L1 is 1.00 / 0.84 / 1.31, i.e. there is no
consistent dimming. So the locked variant is a plain desaturation -- **do not darken it**.

Dimensions are inherited from execute_1.png, so this script never needs to know the icon size.
(Ability icons are specified as 32x32; execute is a 64x64 exception explicitly authorised by the
user -- see section 7.3 of docs/自制龙之生存技能总设计.md.)

Run:
  python tools/make_execute_icons.py             regenerate execute_0.png from execute_1.png
  python tools/make_execute_icons.py --dry-run   report only, write nothing
"""

from __future__ import annotations

import argparse
import os
import sys

from PIL import Image

ABILITY_DIR = os.path.join(
    "src", "main", "resources", "assets", "beloong", "textures", "gui", "sprites", "abilities"
)
SOURCE = "execute_1.png"  # delivered artwork -- never written by this script
TARGET = "execute_0.png"  # derived locked variant


def saturation(img: Image.Image) -> float:
    """Mean HSV saturation (0.0 .. 1.0). Uses a histogram so it stays cheap and avoids Pillow's
    deprecated Image.getdata()."""
    s_channel = img.convert("RGBA").convert("HSV").getchannel("S")
    hist = s_channel.histogram()  # 256 bins
    total = sum(hist)
    if total == 0:
        return 0.0
    return sum(i * count for i, count in enumerate(hist)) / total / 255.0


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--dry-run", action="store_true",
                        help="report what would be written, change nothing")
    args = parser.parse_args()

    src = os.path.join(ABILITY_DIR, SOURCE)
    dst = os.path.join(ABILITY_DIR, TARGET)

    if not os.path.isfile(src):
        print("ERROR: source artwork not found: %s" % src, file=sys.stderr)
        print("       %s is the delivered icon and is never generated by this script;" % SOURCE,
              file=sys.stderr)
        print("       drop the authorised artwork there first (dimensions are inherited from it).",
              file=sys.stderr)
        return 1

    with Image.open(src) as im:
        src_size = im.size
        # convert("L") is ITU-R 601-2 luma (0.299R + 0.587G + 0.114B) => saturation is exactly 0.
        # Converting back to RGBA keeps the on-disk format identical to the other ability icons.
        locked = im.convert("RGBA").convert("L").convert("RGBA")

    sat = saturation(locked)
    print("source : %s  %dx%d" % (SOURCE, src_size[0], src_size[1]))
    print("target : %s  %dx%d  mean saturation=%.3f (expect 0.000)" % (
        TARGET, locked.size[0], locked.size[1], sat))

    if sat > 0.001:
        print("ERROR: output is not grayscale (saturation %.3f)" % sat, file=sys.stderr)
        return 1

    if args.dry_run:
        print("dry-run: nothing written")
        return 0

    locked.save(dst, "PNG", optimize=True)
    print("wrote  : %s (%d bytes)" % (dst, os.path.getsize(dst)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
